name: Build and deploy nuget package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    name: Build solution and run tests

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build Debug
        run: dotnet build --no-restore -c Debug
      - name: Test Debug
        run: dotnet test --no-build --verbosity normal
      - name: Build Release
        run: dotnet build --no-restore -c Release
      - name: Test Release
        run: dotnet test --no-build -c Release --verbosity normal

  publish-nuget:
    runs-on: windows-latest
    name: Build and publish NuGet package
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET with NuGet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
      - name: Get and store tag version name
        run: echo ("CURRENT_TAG=" + $env:GITHUB_REF.Replace('refs/tags/v', '')) >> $env:GITHUB_ENV
      - name: Rebuild nuget package
        run: dotnet build ReplayUnpack.Core -c Release -p:PackageVersion="$env:CURRENT_TAG"
      - name: Publish nuget package
        run: dotnet nuget push "ReplayUnpack.Core\bin\Release\*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_TOKEN }} --skip-duplicate